spring:
  application.name: spring-data-jpa
  datasource:
    url: jdbc:mariadb://localhost:3306/common
    username: common
    password: common_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        "[enable_lazy_load_no_trans]": true
